---
apiVersion: v1
kind: Pod
metadata:
  name: test3
  labels:
    not_a_billing_label: customer1
spec:
  restartPolicy: OnFailure
  containers:
    - name: test3
      image: nginx
      imagePullPolicy: Always